// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_message_id.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace Msg.ClientMessageId {

  #region Enums
  public enum MSGID {
    None = 0,
    /// <summary>
    /// 测试 C2S_TEST_COMMAND
    /// </summary>
    C2STestCommand = 1,
    /// <summary>
    /// 心跳
    /// </summary>
    C2SHeartbeat = 2,
    /// <summary>
    /// 心跳返回
    /// </summary>
    S2CHeartbeat = 3,
    /// <summary>
    /// 红点状态通知
    /// </summary>
    S2CStateNotify = 4,
    /// <summary>
    /// 请求数据同步
    /// </summary>
    C2SDataSyncRequest = 5,
    /// <summary>
    /// 注册账号 C2SRegisterRequest
    /// </summary>
    C2SRegisterRequest = 1000,
    /// <summary>
    /// 注册返回 S2CRegisterResponse
    /// </summary>
    S2CRegisterResponse = 1001,
    /// <summary>
    /// 游客绑定新账号 C2SGuestBindNewAccountRequest
    /// </summary>
    C2SGuestBindNewAccountRequest = 1002,
    /// <summary>
    /// 游客绑定新账号返回 S2CGuestBindNewAccountResponse
    /// </summary>
    S2CGuestBindNewAccountResponse = 1003,
    /// <summary>
    /// 登陆请求 C2SLoginRequest
    /// </summary>
    C2SLoginRequest = 10000,
    /// <summary>
    /// 登陆请求返回  S2CLoginResponse
    /// </summary>
    S2CLoginResponse = 10001,
    /// <summary>
    /// 其他地方登陆 S2COtherPlaceLogin
    /// </summary>
    S2COtherPlaceLogin = 10002,
    /// <summary>
    /// 选择服务器 C2SSelectServerRequest
    /// </summary>
    C2SSelectServerRequest = 10003,
    /// <summary>
    /// 选择服务器返回 S2CSelectServerResponse
    /// </summary>
    S2CSelectServerResponse = 10004,
    /// <summary>
    /// 玩家列表 C2SAccountPlayerListRequest
    /// </summary>
    C2SAccountPlayerListRequest = 10005,
    /// <summary>
    /// 玩家列表返回 S2CAccountPlayerListResponse
    /// </summary>
    S2CAccountPlayerListResponse = 10006,
    /// <summary>
    /// 玩家修改登陆密码 C2SSetLoginPasswordRequest
    /// </summary>
    C2SSetLoginPasswordRequest = 10007,
    /// <summary>
    /// 玩家修改登陆密码返回 S2CSetLoginPasswordResponse
    /// </summary>
    S2CSetLoginPasswordResponse = 10008,
    /// <summary>
    /// 进入游戏 C2SEnterGameRequest
    /// </summary>
    C2SEnterGameRequest = 10020,
    /// <summary>
    /// 进入游戏返回 S2CEnterGameResponse
    /// </summary>
    S2CEnterGameResponse = 10021,
    /// <summary>
    /// 进入游戏完成 S2CEnterGameCompleteNotify
    /// </summary>
    S2CEnterGameCompleteNotify = 10022,
    /// <summary>
    /// 离开游戏 C2SLeaveGameRequest
    /// </summary>
    C2SLeaveGameRequest = 10023,
    /// <summary>
    /// 离开游戏返回 S2CLeaveGameResponse
    /// </summary>
    S2CLeaveGameResponse = 10024,
    /// <summary>
    /// 玩家信息 S2CPlayerInfoResponse
    /// </summary>
    S2CPlayerInfoResponse = 10025,
    /// <summary>
    /// 玩家改名 C2SPlayerChangeNameRequest
    /// </summary>
    C2SPlayerChangeNameRequest = 10026,
    /// <summary>
    /// 玩家改名返回 S2CPlayerChangeNameResponse
    /// </summary>
    S2CPlayerChangeNameResponse = 10027,
    /// <summary>
    /// 换头像 C2SPlayerChangeHeadRequest
    /// </summary>
    C2SPlayerChangeHeadRequest = 10028,
    /// <summary>
    /// 换头像返回 S2CPlayerChangeHeadResponse
    /// </summary>
    S2CPlayerChangeHeadResponse = 10029,
    /// <summary>
    /// 重新连接游戏服务器
    /// </summary>
    C2SReconnectRequest = 10030,
    /// <summary>
    /// 重连返回
    /// </summary>
    S2CReconnectResponse = 10031,
    /// <summary>
    /// 角色请求同步 C2SRolesRequest
    /// </summary>
    C2SRolesRequest = 10050,
    /// <summary>
    /// 角色请求不同返回 S2CRolesResponse
    /// </summary>
    S2CRolesResponse = 10051,
    /// <summary>
    /// 角色更新 S2CRolesChangeNotify
    /// </summary>
    S2CRolesChangeNotify = 10052,
    /// <summary>
    /// 角色属性请求 C2SRoleAttrsRequest
    /// </summary>
    C2SRoleAttrsRequest = 10053,
    /// <summary>
    /// 角色属性请求返回 S2CRoleAttrsResponse
    /// </summary>
    S2CRoleAttrsResponse = 10054,
    /// <summary>
    /// 请求角色升级 C2SRoleLevelUpRequest
    /// </summary>
    C2SRoleLevelupRequest = 10055,
    /// <summary>
    /// 请求角色升级返回 S2CRoleLevelUpResponse
    /// </summary>
    S2CRoleLevelupResponse = 10056,
    /// <summary>
    /// 请求角色升阶 C2SRoleRankUpRequest
    /// </summary>
    C2SRoleRankupRequest = 10057,
    /// <summary>
    /// 请求角色升阶返回 S2CRoleRankUpResponse
    /// </summary>
    S2CRoleRankupResponse = 10058,
    /// <summary>
    /// 请求角色分解 C2SRoleDecomposeRequest
    /// </summary>
    C2SRoleDecomposeRequest = 10059,
    /// <summary>
    /// 请求角色分解返回 S2CRoleDecomposeResponse
    /// </summary>
    S2CRoleDecomposeResponse = 10060,
    /// <summary>
    /// 请求角色合成 C2SRoleFusionRequest
    /// </summary>
    C2SRoleFusionRequest = 10061,
    /// <summary>
    /// 请求角色合成返回 S2CRoleFusionResponse
    /// </summary>
    S2CRoleFusionResponse = 10062,
    /// <summary>
    /// 请求角色锁定 C2SRoleLockRequest
    /// </summary>
    C2SRoleLockRequest = 10063,
    /// <summary>
    /// 请求角色锁定返回 S2CRoleLockResponse
    /// </summary>
    S2CRoleLockResponse = 10064,
    /// <summary>
    /// 请求角色图鉴 C2SRoleHandbookRequest
    /// </summary>
    C2SRoleHandbookRequest = 10065,
    /// <summary>
    /// 请求角色图鉴返回 S2CRoleHandbookResponse
    /// </summary>
    S2CRoleHandbookResponse = 10066,
    /// <summary>
    /// 请求角色左槽开启 C2SRoleLeftSlotOpenRequest
    /// </summary>
    C2SRoleLeftslotOpenRequest = 10067,
    /// <summary>
    /// 请求角色左槽开启返回 S2CRoleLeftSlotOpenResponse
    /// </summary>
    S2CRoleLeftslotOpenResponse = 10068,
    /// <summary>
    /// 请求一键穿戴 C2SRoleOneKeyEquipRequest
    /// </summary>
    C2SRoleOnekeyEquipRequest = 10069,
    /// <summary>
    /// 请求一键穿戴返回 S2CRoleOneKeyEquipResponse
    /// </summary>
    S2CRoleOnekeyEquipResponse = 10070,
    /// <summary>
    /// 请求一键脱装 C2SRoleOneKeyUnequipRequest
    /// </summary>
    C2SRoleOnekeyUnequipRequest = 10071,
    /// <summary>
    /// 请求一键脱装返回 S2CRoleOneKeyUnequipResponse
    /// </summary>
    S2CRoleOnekeyUnequipResponse = 10072,
    /// <summary>
    /// 请求左槽结果保存 C2SRoleLeftSlotResultSaveRequest
    /// </summary>
    C2SRoleLeftslotResultSaveRequest = 10073,
    /// <summary>
    /// 请求左槽结果保存返回 S2CRoleLeftSlotResultSaveResponse
    /// </summary>
    S2CRoleLeftslotResultSaveResponse = 10074,
    /// <summary>
    /// 请求左槽结果取消 C2SRoleLeftSlotResultCancelRequest
    /// </summary>
    C2SRoleLeftslotResultCancelRequest = 10075,
    /// <summary>
    /// 请求左槽结果取消返回 S2CRoleLeftSlotResultCancelResponse
    /// </summary>
    S2CRoleLeftslotResultCancelResponse = 10076,
    /// <summary>
    /// 请求置换 C2SRoleDisplaceRequest
    /// </summary>
    C2SRoleDisplaceRequest = 10077,
    /// <summary>
    /// 请求置换返回 S2CRoleDisplaceResponse
    /// </summary>
    S2CRoleDisplaceResponse = 10078,
    /// <summary>
    /// 请求置换确认 C2SRoleDisplaceConfirmRequest
    /// </summary>
    C2SRoleDisplaceConfirmRequest = 10079,
    /// <summary>
    /// 请求置换确认返回 S2CRoleDisplaceConfirmResponse
    /// </summary>
    S2CRoleDisplaceConfirmResponse = 10080,
    /// <summary>
    /// 战斗结果请求 C2SBattleResultRequest
    /// </summary>
    C2SBattleResultRequest = 10100,
    /// <summary>
    /// 战斗结果请求返回 S2CBattleResultResponse
    /// </summary>
    S2CBattleResultResponse = 10101,
    /// <summary>
    /// 录像数据请求 C2SBattleRecordRequest
    /// </summary>
    C2SBattleRecordRequest = 10102,
    /// <summary>
    /// 录像数据请求返回 S2CBattleRecordResponse
    /// </summary>
    S2CBattleRecordResponse = 10103,
    /// <summary>
    /// 录像数据列表请求 C2SBattleRecordListRequest
    /// </summary>
    C2SBattleRecordListRequest = 10104,
    /// <summary>
    /// 录像数据列表返回 S2CBattleRecordListResponse
    /// </summary>
    S2CBattleRecordListResponse = 10105,
    /// <summary>
    /// 录像删除请求 C2SBattleRecordDeleteRequest
    /// </summary>
    C2SBattleRecordDeleteRequest = 10106,
    /// <summary>
    /// 录像删除返回 S2CBattleRecordDeleteResponse
    /// </summary>
    S2CBattleRecordDeleteResponse = 10107,
    /// <summary>
    /// 战斗随机奖励 S2CBattleRandomRewardNotify
    /// </summary>
    S2CBattleRandomRewardNotify = 10108,
    /// <summary>
    /// 设置阵营 C2SSetTeamRequest
    /// </summary>
    C2SSetTeamRequest = 10200,
    /// <summary>
    /// 设置阵营返回 S2CSetTeamResponse
    /// </summary>
    S2CSetTeamResponse = 10201,
    /// <summary>
    /// 所有阵容列表返回 S2CTeamsResponse
    /// </summary>
    S2CTeamsResponse = 10202,
    /// <summary>
    /// 请求物品同步 C2SItemsSyncRequest
    /// </summary>
    C2SItemsSyncRequest = 10300,
    /// <summary>
    /// 进入游戏物品同步 S2CItemsSync
    /// </summary>
    S2CItemsSync = 10301,
    /// <summary>
    /// 物品更新 S2CItemsUpdate
    /// </summary>
    S2CItemsUpdate = 10302,
    /// <summary>
    /// 物品合成 C2SItemFusionRequest
    /// </summary>
    C2SItemFusionRequest = 10303,
    /// <summary>
    /// 物品合成返回 S2CItemFusionResponse
    /// </summary>
    S2CItemFusionResponse = 10304,
    /// <summary>
    /// 出售物品 C2SItemSellRequest
    /// </summary>
    C2SItemSellRequest = 10305,
    /// <summary>
    /// 出售物品返回 S2CItemSellResponse
    /// </summary>
    S2CItemSellResponse = 10306,
    /// <summary>
    /// 请求装备物品 C2SItemEquipRequest
    /// </summary>
    C2SItemEquipRequest = 10307,
    /// <summary>
    /// 请求装备物品返回 S2CItemEquipResponse
    /// </summary>
    S2CItemEquipResponse = 10308,
    /// <summary>
    /// 请求卸载物品 C2SItemUnequipRequest
    /// </summary>
    C2SItemUnequipRequest = 10309,
    /// <summary>
    /// 请求卸载物品返回 S2CItemUnequipResponse
    /// </summary>
    S2CItemUnequipResponse = 10310,
    /// <summary>
    /// 请求物品升级 C2SItemUpgradeRequest
    /// </summary>
    C2SItemUpgradeRequest = 10311,
    /// <summary>
    /// 请求物品升级返回 S2CItemUpgradeResponse
    /// </summary>
    S2CItemUpgradeResponse = 10312,
    /// <summary>
    /// 请求一键合成装备 C2SItemOneKeyUpgradeRequest
    /// </summary>
    C2SItemOnekeyUpgradeRequest = 10313,
    /// <summary>
    /// 请求一键合成装备返回 S2CItemOneKeyUpgradeResponse
    /// </summary>
    S2CItemOnekeyUpgradeResponse = 10314,
    /// <summary>
    /// 请求战役数据 C2SCampaignDataRequest
    /// </summary>
    C2SCampaignDataRequest = 10400,
    /// <summary>
    /// 战役数据返回 S2CCampaignDataResponse
    /// </summary>
    S2CCampaignDataResponse = 10401,
    /// <summary>
    /// 战役挂机收益请求 C2SCampaignHangupIncomeRequest
    /// </summary>
    C2SCampaignHangupIncomeRequest = 10402,
    /// <summary>
    /// 战役挂机收益返回 S2CCampaignHangupIncomeResponse
    /// </summary>
    S2CCampaignHangupIncomeResponse = 10403,
    /// <summary>
    /// 设置挂机战役ID C2SBattleSetHangupCampaignRequest
    /// </summary>
    C2SBattleSetHangupCampaignRequest = 10404,
    /// <summary>
    /// 设置挂机战役ID返回 S2CBattleSetHangupCampaignResponse
    /// </summary>
    S2CBattleSetHangupCampaignResponse = 10405,
    /// <summary>
    /// 挂机加速请求 C2SCampaignAccelerateIncomeRequest
    /// </summary>
    C2SCampaignAccelerateIncomeRequest = 10406,
    /// <summary>
    /// 挂机请求加速返回 S2CCampaignAccelerateIncomeResponse
    /// </summary>
    S2CCampaignAccelerateIncomeResponse = 10407,
    /// <summary>
    /// 手动刷新加速 C2SCampaignAccelerateRefreshRequest
    /// </summary>
    C2SCampaignAccelerateRefreshRequest = 10408,
    /// <summary>
    /// 手动刷新加速返回 S2CCampaignAccelerateRefreshResponse
    /// </summary>
    S2CCampaignAccelerateRefreshResponse = 10409,
    /// <summary>
    /// 请求发送邮件 C2SMailSendRequest
    /// </summary>
    C2SMailSendRequest = 10500,
    /// <summary>
    /// 发送邮件返回 S2CMailSendResponse
    /// </summary>
    S2CMailSendResponse = 10501,
    /// <summary>
    /// 请求邮件列表 C2SMailListRequest
    /// </summary>
    C2SMailListRequest = 10502,
    /// <summary>
    /// 邮件列表返回 S2CMailListResponse
    /// </summary>
    S2CMailListResponse = 10503,
    /// <summary>
    /// 请求邮件详细内容 C2SMailDetailRequest
    /// </summary>
    C2SMailDetailRequest = 10504,
    /// <summary>
    /// 邮件详细内容返回 S2CMailDetailResponse
    /// </summary>
    S2CMailDetailResponse = 10505,
    /// <summary>
    /// 请求邮件附件获取 C2SMailGetAttachedItemsRequest
    /// </summary>
    C2SMailGetAttachedItemsRequest = 10506,
    /// <summary>
    /// 邮件附件获取返回 S2CMailGetAttachedItemsResponse
    /// </summary>
    S2CMailGetAttachedItemsResponse = 10507,
    /// <summary>
    /// 请求删除邮件 C2SMailDeleteRequest
    /// </summary>
    C2SMailDeleteRequest = 10508,
    /// <summary>
    /// 删除邮件返回 S2CMailDeleteResponse
    /// </summary>
    S2CMailDeleteResponse = 10509,
    /// <summary>
    /// 新邮件通知 S2CMailsNewNotify
    /// </summary>
    S2CMailsNewNotify = 10510,
    /// <summary>
    /// 请求天赋升级 C2STalentUpRequest
    /// </summary>
    C2STalentUpRequest = 10600,
    /// <summary>
    /// 天赋升级返回 S2CTalentUpResponse
    /// </summary>
    S2CTalentUpResponse = 10601,
    /// <summary>
    /// 请求天赋列表 C2STalentListRequest
    /// </summary>
    C2STalentListRequest = 10602,
    /// <summary>
    /// 天赋列表返回 S2CTalentListResponse
    /// </summary>
    S2CTalentListResponse = 10603,
    /// <summary>
    /// 天赋重置 C2STalentResetRequest
    /// </summary>
    C2STalentResetRequest = 10604,
    /// <summary>
    /// 天赋重置返回 S2CTalentResetResponse
    /// </summary>
    S2CTalentResetResponse = 10605,
    /// <summary>
    /// 爬塔数据请求 C2STowerDataRequest
    /// </summary>
    C2STowerDataRequest = 10700,
    /// <summary>
    /// 爬塔数据返回 S2CTowerDataResponse
    /// </summary>
    S2CTowerDataResponse = 10701,
    /// <summary>
    /// 爬塔录像信息请求 C2STowerRecordsInfoRequest
    /// </summary>
    C2STowerRecordsInfoRequest = 10702,
    /// <summary>
    /// 爬塔录像信息返回 S2CTowerRecordsInfoResponse
    /// </summary>
    S2CTowerRecordsInfoResponse = 10703,
    /// <summary>
    /// 爬塔录像具体数据 C2STowerRecordDataRequest
    /// </summary>
    C2STowerRecordDataRequest = 10704,
    /// <summary>
    /// 爬塔录像具体数据返回 S2CTowerRecordDataResponse
    /// </summary>
    S2CTowerRecordDataResponse = 10705,
    /// <summary>
    /// 爬塔排行榜请求 C2STowerRankingListRequest
    /// </summary>
    C2STowerRankingListRequest = 10706,
    /// <summary>
    /// 爬塔排行榜请求返回 S2CTowerRankingListResponse
    /// </summary>
    S2CTowerRankingListResponse = 10707,
    /// <summary>
    /// 请求抽卡 C2SDrawCardRequest
    /// </summary>
    C2SDrawCardRequest = 10800,
    /// <summary>
    /// 请求抽卡返回 S2CDrawCardResponse
    /// </summary>
    S2CDrawCardResponse = 10801,
    /// <summary>
    /// 请求抽卡数据 C2SDrawDataRequest
    /// </summary>
    C2SDrawDataRequest = 10802,
    /// <summary>
    /// 请求抽卡数据返回 S2CDrawDataResponse
    /// </summary>
    S2CDrawDataResponse = 10803,
    /// <summary>
    /// 请求点金 C2STouchGoldRequest
    /// </summary>
    C2STouchGoldRequest = 10900,
    /// <summary>
    /// 请求点金返回 S2CTouchGoldResponse
    /// </summary>
    S2CTouchGoldResponse = 10901,
    /// <summary>
    /// 请求点金手数据 C2SGoldHandDataRequest
    /// </summary>
    C2SGoldHandDataRequest = 10902,
    /// <summary>
    /// 请求点金手数据返回 S2CGoldHandDataResponse
    /// </summary>
    S2CGoldHandDataResponse = 10903,
    /// <summary>
    /// 请求商店数据 C2SShopDataRequest
    /// </summary>
    C2SShopDataRequest = 11000,
    /// <summary>
    /// 请求商店数据返回 S2CShopDataResponse
    /// </summary>
    S2CShopDataResponse = 11001,
    /// <summary>
    /// 请求商店购买 C2SShopBuyItemRequest
    /// </summary>
    C2SShopBuyItemRequest = 11002,
    /// <summary>
    /// 请求商店购买返回 S2CShopBuyItemResponse
    /// </summary>
    S2CShopBuyItemResponse = 11003,
    /// <summary>
    /// 请求商店刷新 C2SShopRefreshRequest
    /// </summary>
    C2SShopRefreshRequest = 11004,
    /// <summary>
    /// 请求商店刷新返回 S2CShopRefreshResponse
    /// </summary>
    S2CShopRefreshResponse = 11005,
    /// <summary>
    /// 商店定时自动刷新通知 S2CShopAutoRefreshNotify
    /// </summary>
    S2CShopAutoRefreshNotify = 11006,
    /// <summary>
    /// 请求排行榜 C2SRankListRequest
    /// </summary>
    C2SRankListRequest = 11100,
    /// <summary>
    /// 排行榜返回 S2CRankListResponse
    /// </summary>
    S2CRankListResponse = 11101,
    /// <summary>
    /// 请求竞技场数据 C2SArenaDataRequest
    /// </summary>
    C2SArenaDataRequest = 11200,
    /// <summary>
    /// 请求竞技场数据返回 S2CAreaDataResponse
    /// </summary>
    S2CArenaDataResponse = 11201,
    /// <summary>
    /// 请求竞技场玩家阵容 C2SArenaPlayerDefenseTeamRequest
    /// </summary>
    C2SArenaPlayerDefenseTeamRequest = 11202,
    /// <summary>
    /// 请求竞技场玩家阵容返回 S2CArenaPlayerDefenseTeamResponse
    /// </summary>
    S2CArenaPlayerDefenseTeamResponse = 11203,
    /// <summary>
    /// 请求竞技场匹配 C2SArenaMatchPlayerRequest
    /// </summary>
    C2SArenaMatchPlayerRequest = 11204,
    /// <summary>
    /// 请求竞技场匹配返回 S2CArenaMatchPlayerResponse
    /// </summary>
    S2CArenaMatchPlayerResponse = 11205,
    /// <summary>
    /// 段位奖励通知 S2CArenaGradeRewardNotify
    /// </summary>
    S2CArenaGradeRewardNotify = 11206,
    /// <summary>
    /// 竞技场比赛积分通知
    /// </summary>
    S2CArenaScoreNotify = 11207,
    /// <summary>
    /// 请求活动副本数据 C2SActiveStageDataRequest
    /// </summary>
    C2SActiveStageDataRequest = 11300,
    /// <summary>
    /// 活动副本数据返回 S2CActiveStageDataResponse
    /// </summary>
    S2CActiveStageDataResponse = 11301,
    /// <summary>
    /// 请求购买活动副本挑战次数 C2SActiveStageChallengeNumBuyRequest
    /// </summary>
    C2SActiveStageBuyChallengeNumRequest = 11302,
    /// <summary>
    /// 购买活动副本挑战次数返回 S2CActiveStageChallengeNumBuyResponse
    /// </summary>
    S2CActiveStageBuyChallengeNumResponse = 11303,
    /// <summary>
    /// 活动副本刷新通知 S2CActiveStageRefreshNotify
    /// </summary>
    S2CActiveStageRefreshNotify = 11304,
    /// <summary>
    /// 活动副本选择好友角色助战 C2SActiveStageSelectAssistRoleRequest
    /// </summary>
    C2SActiveStageSelectAssistRoleRequest = 11305,
    /// <summary>
    /// 活动副本选择好友助战返回 S2CActiveStageSelectAssistRoleResponse
    /// </summary>
    S2CActiveStageSelectAssistRoleResponse = 11306,
    /// <summary>
    /// 活动副本获取好友的助战角色列表 C2SFriendsAssistRoleListRequest
    /// </summary>
    C2SActiveStageAssistRoleListRequest = 11307,
    /// <summary>
    /// 活动副本获取好友助战角色列表返回 S2CFriendAssistRoleListResponse
    /// </summary>
    S2CActiveStageAssistRoleListResponse = 11308,
    /// <summary>
    /// 请求好友推荐 C2SFriendRecommendRequest
    /// </summary>
    C2SFriendRecommendRequest = 11400,
    /// <summary>
    /// 好友推荐返回 S2CFriendRecommendResponse
    /// </summary>
    S2CFriendRecommendResponse = 11401,
    /// <summary>
    /// 请求好友列表 C2SFriendListRequest
    /// </summary>
    C2SFriendListRequest = 11402,
    /// <summary>
    /// 好友列表返回 S2CFriendListResponse
    /// </summary>
    S2CFriendListResponse = 11403,
    /// <summary>
    /// 请求申请好友 C2SFriendAskRequest
    /// </summary>
    C2SFriendAskRequest = 11404,
    /// <summary>
    /// 申请好友返回 S2CFriendFriendAskResponse
    /// </summary>
    S2CFriendAskResponse = 11405,
    /// <summary>
    /// 请求获得好友申请列表 C2SFriendAskPlayerListRequest
    /// </summary>
    C2SFriendAskPlayerListRequest = 11406,
    /// <summary>
    /// 获得好友申请列表返回 S2CFriendAskPlayerListResponse
    /// </summary>
    S2CFriendAskPlayerListResponse = 11407,
    /// <summary>
    /// 好友列表增加通知 S2CFriendAskPlayerListAddNotify
    /// </summary>
    S2CFriendAskPlayerListAddNotify = 11408,
    /// <summary>
    /// 请求同意添加好友 C2SFriendAgreeRequest
    /// </summary>
    C2SFriendAgreeRequest = 11409,
    /// <summary>
    /// 同意添加好友返回 S2CFriendAgreeResponse
    /// </summary>
    S2CFriendAgreeResponse = 11410,
    /// <summary>
    /// 好友列表增加通知 S2CFriendListAddNotify
    /// </summary>
    S2CFriendListAddNotify = 11411,
    /// <summary>
    /// 请求拒绝添加好友 C2SFriendRefuseRequest
    /// </summary>
    C2SFriendRefuseRequest = 11412,
    /// <summary>
    /// 拒绝添加好友返回 S2CFriendRefuseResponse
    /// </summary>
    S2CFriendRefuseResponse = 11413,
    /// <summary>
    /// 请求删除好友 C2SFriendRemoveRequest
    /// </summary>
    C2SFriendRemoveRequest = 11414,
    /// <summary>
    /// 删除好友返回 S2CFriendRemoveResponse
    /// </summary>
    S2CFriendRemoveResponse = 11415,
    /// <summary>
    /// 请求赠送友情点 C2SFriendGivePointsRequest
    /// </summary>
    C2SFriendGivePointsRequest = 11416,
    /// <summary>
    /// 赠送友情点返回 S2CFriendGivePointsResponse
    /// </summary>
    S2CFriendGivePointsResponse = 11417,
    /// <summary>
    /// 请求领取友情点 C2SFriendGetPointsRequest
    /// </summary>
    C2SFriendGetPointsRequest = 11418,
    /// <summary>
    /// 领取友情点返回 S2CFriendGetPointsResponse
    /// </summary>
    S2CFriendGetPointsResponse = 11419,
    /// <summary>
    /// 请求搜索好友BOSS C2SFriendSearchBossRequest
    /// </summary>
    C2SFriendSearchBossRequest = 11420,
    /// <summary>
    /// 返回搜索好友BOSS S2CFriendSearchBossResponse
    /// </summary>
    S2CFriendSearchBossResponse = 11421,
    /// <summary>
    /// 请求好友BOSS列表 C2SFriendsBossListRequest
    /// </summary>
    C2SFriendsBossListRequest = 11422,
    /// <summary>
    /// 好友BOSS列表返回 S2CFriendsBossListResponse
    /// </summary>
    S2CFriendsBossListResponse = 11423,
    /// <summary>
    /// 获取好友BOSS助战列表 C2SFriendBossAttackListRequest
    /// </summary>
    C2SFriendBossAttackListRequest = 11424,
    /// <summary>
    /// 获取好友BOSS助战列表返回 S2CFriendBossAttackListResponse
    /// </summary>
    S2CFriendBossAttackListResponse = 11425,
    /// <summary>
    /// 好友相关数据 C2SFriendDataRequest
    /// </summary>
    C2SFriendDataRequest = 11426,
    /// <summary>
    /// 好友相关数据返回 S2CFriendDataResponse
    /// </summary>
    S2CFriendDataResponse = 11427,
    /// <summary>
    ///S2C_FRIEND_BOSS_ATTACK_REWARD_NOTIFY	= 11428; // 好友BOSS击打奖励通知 S2CFriendBossAttackRewardNotify
    /// </summary>
    C2SFriendSetAssistRoleRequest = 11429,
    /// <summary>
    /// 设置助战角色返回 S2CFriendSetAssistRoleResponse
    /// </summary>
    S2CFriendSetAssistRoleResponse = 11430,
    /// <summary>
    /// 一键收发友情点 C2SFriendGiveAndGetPointsRequest
    /// </summary>
    C2SFriendGiveAndGetPointsRequest = 11431,
    /// <summary>
    /// 助战获取友情点 C2SFriendGetAssistPointsRequest
    /// </summary>
    C2SFriendGetAssistPointsRequest = 11432,
    /// <summary>
    /// 助战获取友情点返回 S2CFriendGetAssistPointsResponse
    /// </summary>
    S2CFriendGetAssistPointsResponse = 11433,
    /// <summary>
    /// 好友删除通知 S2CFriendRemoveNotify
    /// </summary>
    S2CFriendRemoveNotify = 11434,
    /// <summary>
    /// 请求任务数据 C2STaskDataRequest
    /// </summary>
    C2STaskDataRequest = 11500,
    /// <summary>
    /// 任务数据返回 S2CTaskDataResponse
    /// </summary>
    S2CTaskDataResponse = 11501,
    /// <summary>
    /// 任务数据通知 S2CTaskValueNotify
    /// </summary>
    S2CTaskValueNotify = 11502,
    /// <summary>
    /// 请求任务奖励 C2STaskRewardRequest
    /// </summary>
    C2STaskRewardRequest = 11503,
    /// <summary>
    /// 任务奖励返回 S2CTaskRewardResponse
    /// </summary>
    S2CTaskRewardResponse = 11504,
    /// <summary>
    /// 请求探索任务数据 C2SExploreDataRequest
    /// </summary>
    C2SExploreDataRequest = 11600,
    /// <summary>
    /// 探索任务数据返回 S2CExploreDataResponse
    /// </summary>
    S2CExploreDataResponse = 11601,
    /// <summary>
    /// 选择探索角色 C2SExploreSelRoleRequest
    /// </summary>
    C2SExploreSelRoleRequest = 11602,
    /// <summary>
    /// 选择探索角色返回 S2CExploreSelRoleResponse
    /// </summary>
    S2CExploreSelRoleResponse = 11603,
    /// <summary>
    /// 开始探索 C2SExploreStartRequest
    /// </summary>
    C2SExploreStartRequest = 11604,
    /// <summary>
    /// 开始探索返回 S2CExploreStartResponse
    /// </summary>
    S2CExploreStartResponse = 11605,
    /// <summary>
    /// 加速任务 C2SExploreSpeedupRequest
    /// </summary>
    C2SExploreSpeedupRequest = 11606,
    /// <summary>
    /// 加速任务返回 S2CExploreSpeedupResponse
    /// </summary>
    S2CExploreSpeedupResponse = 11607,
    /// <summary>
    /// 刷新探索任务 C2SExploreRefreshRequest
    /// </summary>
    C2SExploreRefreshRequest = 11608,
    /// <summary>
    /// 刷新探索任务返回 S2CExploreRefreshResponse
    /// </summary>
    S2CExploreRefreshResponse = 11609,
    /// <summary>
    /// 自动刷新通知 S2CExploreAutoRefreshNotify
    /// </summary>
    S2CExploreAutoRefreshNotify = 11610,
    /// <summary>
    /// 锁定探索任务 C2SExploreLockRequest
    /// </summary>
    C2SExploreLockRequest = 11611,
    /// <summary>
    /// 锁定探索任务返回 S2CExploreLockResponse
    /// </summary>
    S2CExploreLockResponse = 11612,
    /// <summary>
    /// 探索任务奖励 C2SExploreGetRewardRequest
    /// </summary>
    C2SExploreGetRewardRequest = 11613,
    /// <summary>
    /// 探索任务奖励返回 S2CExploreGetRewardResponse
    /// </summary>
    S2CExploreGetRewardResponse = 11614,
    /// <summary>
    /// 剧情探索任务通知 S2CExploreStoryNewNotify
    /// </summary>
    S2CExploreStoryNewNotify = 11615,
    /// <summary>
    /// 剧情任务删除通知 S2CExploreRemoveNotify
    /// </summary>
    S2CExploreRemoveNotify = 11616,
    /// <summary>
    /// 取消探索任务 C2SExploreCancelRequest
    /// </summary>
    C2SExploreCancelRequest = 11617,
    /// <summary>
    /// 取消探索任务返回 S2CExploreCancelResponse
    /// </summary>
    S2CExploreCancelResponse = 11618,
    /// <summary>
    /// 聊天请求 C2SChatRequest
    /// </summary>
    C2SChatRequest = 11700,
    /// <summary>
    /// 聊天返回 S2CChatResponse
    /// </summary>
    S2CChatResponse = 11701,
    /// <summary>
    /// 拉取聊天消息 C2SChatMsgPullRequest
    /// </summary>
    C2SChatMsgPullRequest = 11702,
    /// <summary>
    /// 拉取聊天消息返回 S2CChatPullMsgResponse
    /// </summary>
    S2CChatMsgPullResponse = 11703,
    /// <summary>
    /// 公会数据 C2SGuildDataRequest
    /// </summary>
    C2SGuildDataRequest = 11800,
    /// <summary>
    /// 公会数据返回 S2CGuildDataResponse
    /// </summary>
    S2CGuildDataResponse = 11801,
    /// <summary>
    /// 搜索公会 C2SGuildSearchRequest
    /// </summary>
    C2SGuildSearchRequest = 11802,
    /// <summary>
    /// 搜索公会返回 S2CGuildSearchResponse
    /// </summary>
    S2CGuildSearchResponse = 11803,
    /// <summary>
    /// 推荐公会 C2SGuildRecommendRequest
    /// </summary>
    C2SGuildRecommendRequest = 11804,
    /// <summary>
    /// 推荐公会返回 S2CGuildRecommendResponse
    /// </summary>
    S2CGuildRecommendResponse = 11805,
    /// <summary>
    /// 创建公会 C2SGuildCreateRequest
    /// </summary>
    C2SGuildCreateRequest = 11806,
    /// <summary>
    /// 创建公会返回 S2CGuildCreateResponse
    /// </summary>
    S2CGuildCreateResponse = 11807,
    /// <summary>
    /// 解散公会 C2SGuildDismissRequest
    /// </summary>
    C2SGuildDismissRequest = 11808,
    /// <summary>
    /// 解散公会返回 S2CGuildDismissResponse
    /// </summary>
    S2CGuildDismissResponse = 11809,
    /// <summary>
    /// 取消解散公会 C2SGuildCancelDismissRequest
    /// </summary>
    C2SGuildCancelDismissRequest = 11810,
    /// <summary>
    /// 取消解散公会返回 S2CGuildCancelDismissResponse
    /// </summary>
    S2CGuildCancelDismissResponse = 11811,
    /// <summary>
    /// 公会删除通知 S2CGuildDeleteNotify
    /// </summary>
    S2CGuildDeleteNotify = 11812,
    /// <summary>
    /// 公会信息修改 C2SGuildInfoModifyRequest
    /// </summary>
    C2SGuildInfoModifyRequest = 11813,
    /// <summary>
    /// 公会信息修改返回 S2CGuildInfoModifyResponse
    /// </summary>
    S2CGuildInfoModifyResponse = 11814,
    /// <summary>
    /// 公会修改公告 C2SGuildAnouncementRequest
    /// </summary>
    C2SGuildAnouncementRequest = 11815,
    /// <summary>
    /// 公会修改公告返回 S2CGuildAnouncementResponse
    /// </summary>
    S2CGuildAnouncementResponse = 11816,
    /// <summary>
    /// 公会成员列表 C2SGuildMembersRequest
    /// </summary>
    C2SGuildMembersRequest = 11817,
    /// <summary>
    /// 公会成员列表返回 S2CGuildMembersResponse
    /// </summary>
    S2CGuildMembersResponse = 11818,
    /// <summary>
    /// 公会申请列表 C2SGuildAskListRequest
    /// </summary>
    C2SGuildAskListRequest = 11819,
    /// <summary>
    /// 公会申请列表返回 S2CGuildAskListResponse
    /// </summary>
    S2CGuildAskListResponse = 11820,
    /// <summary>
    /// 申请加入公会 C2SGuildAskJoinRequest
    /// </summary>
    C2SGuildAskJoinRequest = 11821,
    /// <summary>
    /// 申请加入公会返回 S2CGuildAskJoinResponse
    /// </summary>
    S2CGuildAskJoinResponse = 11822,
    /// <summary>
    /// 同意加入公会 C2SGuildAgreeJoinRequest
    /// </summary>
    C2SGuildAgreeJoinRequest = 11823,
    /// <summary>
    /// 同意加入公会返回 S2CGuildAgreeJoinResponse
    /// </summary>
    S2CGuildAgreeJoinResponse = 11824,
    /// <summary>
    /// 同意加入公会通知 S2CGuildAgreeJoinNotify
    /// </summary>
    S2CGuildAgreeJoinNotify = 11825,
    /// <summary>
    /// 主动退出公会 C2SGuildQuitRequest
    /// </summary>
    C2SGuildQuitRequest = 11826,
    /// <summary>
    /// 退出公会返回 S2C_GUILD_QUIT_RESPONSE
    /// </summary>
    S2CGuildQuitResponse = 11827,
    /// <summary>
    /// 公会日志 C2SGuildLogsRequest
    /// </summary>
    C2SGuildLogsRequest = 11828,
    /// <summary>
    /// 公会日志返回 S2CGuildLogsResponse
    /// </summary>
    S2CGuildLogsResponse = 11829,
    /// <summary>
    /// 公会签到 C2SGuildSignRequest
    /// </summary>
    C2SGuildSignInRequest = 11830,
    /// <summary>
    /// 公会签到返回 S2CGuildSignResponse
    /// </summary>
    S2CGuildSignInResponse = 11831,
    /// <summary>
    /// 公会任免官员 C2SGuildSetOfficerRequest
    /// </summary>
    C2SGuildSetOfficerRequest = 11832,
    /// <summary>
    /// 公会任免官员返回 S2CGuildSetOfficerResponse
    /// </summary>
    S2CGuildSetOfficerResponse = 11833,
    /// <summary>
    /// 公会任命罢免通知 S2CGuildSetOfficerNotify
    /// </summary>
    S2CGuildSetOfficerNotify = 11834,
    /// <summary>
    /// 公会驱逐会员 C2SGuildKickMemberRequest
    /// </summary>
    C2SGuildKickMemberRequest = 11835,
    /// <summary>
    /// 公会驱逐会员返回 S2CGuildKickMemberResponse
    /// </summary>
    S2CGuildKickMemberResponse = 11836,
    /// <summary>
    /// 公会驱逐会员通知 S2CGuildKickMemberNotify
    /// </summary>
    S2CGuildKickMemberNotify = 11837,
    /// <summary>
    /// 公会转让会长 C2SGuildChangePresidentRequest
    /// </summary>
    C2SGuildChangePresidentRequest = 11838,
    /// <summary>
    /// 公会转让会长返回 S2CGuildChangePresidentResponse
    /// </summary>
    S2CGuildChangePresidentResponse = 11839,
    /// <summary>
    /// 公会转让会长通知 S2CGuildChangePresidentNotify
    /// </summary>
    S2CGuildChangePresidentNotify = 11840,
    /// <summary>
    /// 公会招募 C2SGuildRecruitRequest
    /// </summary>
    C2SGuildRecruitRequest = 11841,
    /// <summary>
    /// 公会招募返回 S2CGuildRecruitResponse
    /// </summary>
    S2CGuildRecruitResponse = 11842,
    /// <summary>
    /// 公会请求捐赠 C2SGuildAskDonateRequest
    /// </summary>
    C2SGuildAskDonateRequest = 11843,
    /// <summary>
    /// 公会请求招募返回 S2CGuildAskDonateResponse
    /// </summary>
    S2CGuildAskDonateResponse = 11844,
    /// <summary>
    /// 公会捐赠 C2SGuildDonateRequest
    /// </summary>
    C2SGuildDonateRequest = 11845,
    /// <summary>
    /// 公会捐赠返回 S2CGuildDonateResponse
    /// </summary>
    S2CGuildDonateResponse = 11846,
    /// <summary>
    /// 公会通知请求捐赠物品变化 S2CGuildDonateItemNotify
    /// </summary>
    S2CGuildDonateItemNotify = 11847,
    /// <summary>
    /// 公会捐赠列表 C2SGuildDonateListRequest
    /// </summary>
    C2SGuildDonateListRequest = 11848,
    /// <summary>
    /// 公会捐赠列表 S2CGuildDonateListResponse
    /// </summary>
    S2CGuildDonateListResponse = 11849,
    /// <summary>
    /// 公会副本数据 C2SGuildStageDataRequest
    /// </summary>
    C2SGuildStageDataRequest = 11900,
    /// <summary>
    /// 公会副本数据返回 S2CGuildStageDataResponse
    /// </summary>
    S2CGuildStageDataResponse = 11901,
    /// <summary>
    /// 公会副本排行榜 C2SGuildStageRankListRequest
    /// </summary>
    C2SGuildStageRankListRequest = 11902,
    /// <summary>
    /// 公会副本排行榜返回 S2CGuildStageRankListResponse
    /// </summary>
    S2CGuildStageRankListResponse = 11903,
    /// <summary>
    /// 公会副本玩家复活 C2SGuildStagePlayerRespawnRequest
    /// </summary>
    C2SGuildStagePlayerRespawnRequest = 11904,
    /// <summary>
    /// 公会副本玩家复活返回 S2CGuildStagePlayerRespawnResponse
    /// </summary>
    S2CGuildStagePlayerRespawnResponse = 11905,
    /// <summary>
    /// 公会副本重置 C2SGuildStageResetRequest
    /// </summary>
    C2SGuildStageResetRequest = 11906,
    /// <summary>
    /// 公会副本重置返回 S2CGuildStageResetResponse
    /// </summary>
    S2CGuildStageResetResponse = 11907,
    /// <summary>
    /// 公会副本数据重置通知 S2CGuildStageResetNotify
    /// </summary>
    S2CGuildStageResetNotify = 11908,
    /// <summary>
    /// 公会副本数据自动刷新通知 S2CGuildStageAutoRefreshNotify
    /// </summary>
    S2CGuildStageAutoRefreshNotify = 11909,
    /// <summary>
    /// 签到数据请求 C2SSignDataRequest
    /// </summary>
    C2SSignDataRequest = 12000,
    /// <summary>
    /// 签到数据请求返回 S2CSignDataResponse
    /// </summary>
    S2CSignDataResponse = 12001,
    /// <summary>
    /// 签到领奖 C2SSignAwardRequest
    /// </summary>
    C2SSignAwardRequest = 12002,
    /// <summary>
    /// 签到领奖返回 S2CSignAwardResponse
    /// </summary>
    S2CSignAwardResponse = 12003,
    /// <summary>
    /// 七天乐数据请求 C2SSevenDaysDataRequest
    /// </summary>
    C2SSevendaysDataRequest = 12100,
    /// <summary>
    /// 七天乐数据请求返回 S2CSevenDaysDataResponse
    /// </summary>
    S2CSevendaysDataResponse = 12101,
    /// <summary>
    /// 七天乐领奖请求 C2SSevenDaysAwardRequest
    /// </summary>
    C2SSevendaysAwardRequest = 12102,
    /// <summary>
    /// 七天乐领奖返回 S2CSevenDaysAwardResponse
    /// </summary>
    S2CSevendaysAwardResponse = 12103,
    /// <summary>
    /// 充值数据请求 C2SChargeDataRequest
    /// </summary>
    C2SChargeDataRequest = 12200,
    /// <summary>
    /// 充值数据返回 S2CChargeDataResponse
    /// </summary>
    S2CChargeDataResponse = 12201,
    /// <summary>
    /// 充值请求 C2SChargeRequest
    /// </summary>
    C2SChargeRequest = 12202,
    /// <summary>
    /// 充值返回 S2CChargeResponse
    /// </summary>
    S2CChargeResponse = 12203,
    /// <summary>
    /// 首充奖励通知 S2CChargeFirstRewardNotify
    /// </summary>
    S2CChargeFirstRewardNotify = 12204,
    /// <summary>
    /// 首充领奖 C2SChargeFirstAwardRequest
    /// </summary>
    C2SChargeFirstAwardRequest = 12205,
    /// <summary>
    /// 首充领奖返回 S2CChargeFirstAwardResponse
    /// </summary>
    S2CChargeFirstAwardResponse = 12206,
    /// <summary>
    /// 红点状态请求 C2SRedPointStatesRequest
    /// </summary>
    C2SRedPointStatesRequest = 12300,
    /// <summary>
    /// 红点状态返回 S2CRedPointStatesResponse
    /// </summary>
    S2CRedPointStatesResponse = 12301,
    /// <summary>
    /// 保存引导数据 C2SGuideDataSaveRequest
    /// </summary>
    C2SGuideDataSaveRequest = 12400,
    /// <summary>
    /// 保存引导数据返回 S2CGuideDataSaveResponse
    /// </summary>
    S2CGuideDataSaveResponse = 12401,
    /// <summary>
    /// 引导数据 S2CGuideDataResponse
    /// </summary>
    S2CGuideDataResponse = 12410,
    /// <summary>
    /// 活动数据 C2SActivityDataRequest
    /// </summary>
    C2SActivityDataRequest = 12500,
    /// <summary>
    /// 活动数据返回 S2CActivityDataResponse
    /// </summary>
    S2CActivityDataResponse = 12501,
    /// <summary>
    /// 活动数据通知 S2CActivityDataNotify
    /// </summary>
    S2CActivityDataNotify = 12504,
    /// <summary>
    /// 活动兑换 C2SActivityExchangeRequest
    /// </summary>
    C2SActivityExchangeRequest = 12505,
    /// <summary>
    /// 活动兑换返回 S2CActivityExchangeResponse
    /// </summary>
    S2CActivityExchangeResponse = 12506,
    /// <summary>
    /// 远征数据 C2SExpeditionDataRequest
    /// </summary>
    C2SExpeditionDataRequest = 12600,
    /// <summary>
    /// 远征数据返回 S2CExpeditionDataResponse
    /// </summary>
    S2CExpeditionDataResponse = 12601,
    /// <summary>
    /// 远征关卡数据 C2SExpeditionLevelDataRequest
    /// </summary>
    C2SExpeditionLevelDataRequest = 12602,
    /// <summary>
    /// 远征关卡数据返回 S2CExpeditionLevelDataResponse
    /// </summary>
    S2CExpeditionLevelDataResponse = 12603,
    /// <summary>
    /// 远征当前关卡同步 S2CExpeditionCurrLevelSync
    /// </summary>
    S2CExpeditionCurrLevelSync = 12604,
    /// <summary>
    /// 远征净化点奖励 C2SExpeditionPurifyRewardRequest
    /// </summary>
    C2SExpeditionPurifyRewardRequest = 12605,
    /// <summary>
    /// 远征净化点奖励返回 S2CExpeditionPurifyRewardResponse
    /// </summary>
    S2CExpeditionPurifyRewardResponse = 12606,
    /// <summary>
    /// 远征净化点同步 S2CExpeditionPurifyPointsSync
    /// </summary>
    S2CExpeditionPurifyPointsSync = 12607,
    /// <summary>
    /// 神器数据 C2SArtifactDataRequest
    /// </summary>
    C2SArtifactDataRequest = 12700,
    /// <summary>
    /// 返回神器数据 S2CArtifactDataResponse
    /// </summary>
    S2CArtifactDataResponse = 12701,
    /// <summary>
    /// 神器解锁 C2SArtifactUnlockRequest
    /// </summary>
    C2SArtifactUnlockRequest = 12702,
    /// <summary>
    /// 神器解锁返回 S2CArtifactUnlockResponse
    /// </summary>
    S2CArtifactUnlockResponse = 12703,
    /// <summary>
    /// 神器升级 C2SArtifactLevelUpRequest
    /// </summary>
    C2SArtifactLevelupRequest = 12704,
    /// <summary>
    /// 神器升级返回 S2CArtifactLevelUpResponse
    /// </summary>
    S2CArtifactLevelupResponse = 12705,
    /// <summary>
    /// 神器升阶 C2SArtifactRankUpRequest
    /// </summary>
    C2SArtifactRankupRequest = 12706,
    /// <summary>
    /// 神器升阶返回 S2CArtifactRankUpResponse
    /// </summary>
    S2CArtifactRankupResponse = 12707,
    /// <summary>
    /// 神器重铸 C2SArtifactResetRequest
    /// </summary>
    C2SArtifactResetRequest = 12708,
    /// <summary>
    /// 神器重铸返回 S2CArtifactResetResponse
    /// </summary>
    S2CArtifactResetResponse = 12709,
    /// <summary>
    /// 神器数据更新通知 S2CArtifactDataUpdateNotify
    /// </summary>
    S2CArtifactDataUpdateNotify = 12710,
    /// <summary>
    /// 嘉年华数据 C2SCarnivalDataRequest
    /// </summary>
    C2SCarnivalDataRequest = 12800,
    /// <summary>
    /// 返回嘉年华数据 S2CCarnivalDataResponse
    /// </summary>
    S2CCarnivalDataResponse = 12801,
    /// <summary>
    /// 请求任务进度加1 C2SCarnivalTaskSetRequest
    /// </summary>
    C2SCarnivalTaskSetRequest = 12802,
    /// <summary>
    /// 任务进度加1返回 S2CCarnivalTaskSetResponse
    /// </summary>
    S2CCarnivalTaskSetResponse = 12803,
    /// <summary>
    /// 请求物品兑换 C2SCarnivalItemExchangeRequest
    /// </summary>
    C2SCarnivalItemExchangeRequest = 12804,
    /// <summary>
    /// 物品兑换返回 S2CCarnivalItemExchangeResponse
    /// </summary>
    S2CCarnivalItemExchangeResponse = 12805,
    /// <summary>
    /// 请求分享 C2SCarnivalInviteCodeRequest
    /// </summary>
    C2SCarnivalShareRequest = 12806,
    /// <summary>
    /// 请求分享返回 S2CCarnivalInviteCodeResponse
    /// </summary>
    S2CCarnivalShareResponse = 12807,
    /// <summary>
    /// 请求被邀请验证 C2SCarnivalBeInvitedRequest
    /// </summary>
    C2SCarnivalBeInvitedRequest = 12808,
    /// <summary>
    /// 被邀请验证返回 S2CCarnivalBeInvitedResponse
    /// </summary>
    S2CCarnivalBeInvitedResponse = 12809,
    /// <summary>
    /// 任务数据通知 S2CCarnivalTaskDataNotify
    /// </summary>
    S2CCarnivalTaskDataNotify = 12810,
  }

  #endregion

}

#endregion Designer generated code
